const DELAY = 3000;
const ADDITONAL_DELAY = 5000;
const COMMETNS_QUANTITY = 3;
const MIN_PHONE_LENGTH = 11;
const MAX_PHONE_LENGTH = 12;
const PHONE_REGEXP = /[^\d | +]/;

export {DELAY, ADDITONAL_DELAY, COMMETNS_QUANTITY, MIN_PHONE_LENGTH, MAX_PHONE_LENGTH, PHONE_REGEXP};
